import { WORLD_VERSION, migratePosition } from '../data/world-space.js';
// Sauvegarde locale (navigateur) : personnages, réglages, état du monde (bots). Code d'export/import.
import { G } from './state.js';

const KEY = 'orvalis.save.v1';
let cache = null;
let soonT = null;

function load() {
  if (cache) return cache;
  let data = null;
  try { data = JSON.parse(localStorage.getItem(KEY) || 'null'); } catch (e) { data = null; }
  if (!data || typeof data !== 'object') data = { chars: [], settings: {}, world: {} };
  data.chars ||= []; data.settings ||= {}; data.world ||= {};
  if((data.worldVersion||1)<WORLD_VERSION){
    // Keep the untouched legacy save before the first coordinate conversion.
    try { const raw = localStorage.getItem(KEY); if(raw && !localStorage.getItem(KEY+'.before-world-v2')) localStorage.setItem(KEY+'.before-world-v2',raw); } catch {}
    for(const c of data.chars) migratePosition(c);
    // Serialized bots store XP in `x`; positions are regenerated by Bots.init.
    data.worldVersion=WORLD_VERSION;
  }
  cache = data;
  return data;
}

function write() {
  const data = load();
  try { localStorage.setItem(KEY, JSON.stringify(data)); return true; } catch (e) { return false; }
}

export const Save = {
  load,
  chars() { return load().chars; },
  settings() { return load().settings; },
  world() { return load().world; },
  lastId() { return load().lastId; },

  saveSettings() {
    load().settings = { ...G.settings };
    write();
  },

  saveNow() {
    const data = load();
    const P = G.player;
    if (P) {
      const d = P.data;
      d.level = P.level;
      d.saved = Date.now();
      const i = data.chars.findIndex((c) => c.id === d.id);
      if (i >= 0) data.chars[i] = d; else data.chars.push(d);
      data.lastId = d.id;
    }
    if (G.bots) data.world.bots = G.bots.serialize();
    write();
  },

  saveSoon() {
    clearTimeout(soonT);
    soonT = setTimeout(() => Save.saveNow(), 1500);
  },

  remove(id) {
    const data = load();
    data.chars = data.chars.filter((c) => c.id !== id);
    if (data.lastId === id) data.lastId = data.chars[0]?.id;
    write();
  },

  addChar(d) {
    const data = load();
    data.chars.push(d);
    data.lastId = d.id;
    write();
  },

  exportCode() {
    const P = G.player;
    if (P) this.saveNow();
    const d = P ? P.data : load().chars.find((c) => c.id === load().lastId);
    if (!d) return '';
    const json = JSON.stringify({ o: 'orvalis', v: 1, c: d });
    return 'ORV1.' + btoa(unescape(encodeURIComponent(json)));
  },

  importCode(code) {
    try {
      if (!code.startsWith('ORV1.')) return false;
      const obj = JSON.parse(decodeURIComponent(escape(atob(code.slice(5)))));
      if (obj.o !== 'orvalis' || !obj.c || !obj.c.cls || !obj.c.name) return false;
      const d = obj.c;
      const data = load();
      if (data.chars.some((c) => c.id === d.id)) d.id = 'c' + Date.now().toString(36);
      data.chars.push(d);
      write();
      return true;
    } catch (e) {
      return false;
    }
  },
};

export function initSave() {
  const s = Save.settings();
  Object.assign(G.settings, s);
  G.saveNow = () => Save.saveNow();
  G.saveSoon = () => Save.saveSoon();
  G.saveSettings = () => Save.saveSettings();
  G.exportSave = () => Save.exportCode();
  G.importSave = (c) => Save.importCode(c);
  setInterval(() => { if (G.mode === 'game' && G.player) Save.saveNow(); }, 30000);
  window.addEventListener('beforeunload', () => { if (G.mode === 'game' && G.player) Save.saveNow(); });
  document.addEventListener('visibilitychange', () => { if (document.hidden && G.mode === 'game' && G.player) Save.saveNow(); });
  // republication de l'artifact : on transmet la partie en cours
  try {
    window.claude?.hot?.snapshot?.(() => {
      if (G.mode === 'game' && G.player) Save.saveNow();
      return { save: load(), playing: G.mode === 'game' ? G.player?.data.id : null };
    });
  } catch (e) { /* facultatif */ }
}
