// Écran d'accueil : connexion, cinématique, création, sélection, suppression.
export default async ({ page, shot, wait, ev, key }) => {
  await wait(1500);
  await shot('w1_login');
  await page.click('#tl-cine');
  await wait(4000);
  await shot('w1_cine');
  await key('Escape');
  await wait(600);
  await page.fill('#tl-acct', 'Allan');
  await page.click('#tl-go');
  await wait(1200);
  await shot('w1_create_default');
  await page.click('[data-c="chaman"]');
  await page.click('[data-f="1"]');
  await wait(900);
  await shot('w1_create_braise_chaman');
  await page.click('#cc-dice');
  await wait(300);
  const nm = await ev(() => document.getElementById('cc-name').value);
  console.log('nom aléatoire', nm);
  await page.click('#cc-go');
  await wait(2500);
  console.log(JSON.stringify(await ev(() => ({ mode: window.__dbg.G.mode, name: window.__dbg.G.player?.name, cls: window.__dbg.G.player?.cls }))));
  // retour à l'écran de sélection puis 2e personnage
  await ev(() => window.__dbg.G.toTitle());
  await wait(1200);
  await shot('w1_select_one');
  await page.click('#tt-new');
  await wait(600);
  await page.click('[data-c="templier"]');
  await page.fill('#cc-name', 'Aurélien');
  await wait(600);
  await shot('w1_create_templier');
  await page.click('#cc-go');
  await wait(2000);
  await ev(() => window.__dbg.G.toTitle());
  await wait(1500);
  await shot('w1_select_two');
  await key('ArrowDown');
  await wait(900);
  await shot('w1_select_other');
  await page.click('#tt-del');
  await wait(300);
  await page.fill('#td-in', 'supprimer');
  await wait(200);
  await shot('w1_delete');
  await page.click('#td-y');
  await wait(900);
  console.log(JSON.stringify(await ev(() => ({ chars: document.querySelectorAll('#title .ch').length, mode: document.getElementById('title').className }))));
  await page.click('#ts-back');
  await wait(600);
  await page.click('#tl-opt');
  await wait(300);
  await shot('w1_options');
};
