export { MAX_BONE_INFLUENCES, MODEL_VERTEX_BYTES, MODEL_VERTEX_LAYOUT, MODEL_VERTEX_OFFSETS, modelBounds, ModelMeshBuilder, packModelVertices, validateModelMesh } from './modelMesh';
export type { ModelBounds, ModelMesh } from './modelMesh';
export { ribbonTexture, TREE_RIBBON, particleTexture, TREE_PARTICLE_EMITTERS, ATTACHMENT_ID, buildOrnamentModel, ORNAMENT, ORNAMENT_SKELETON, ornamentTexture, TREE_ATTACHMENTS, buildSwatchModel, buildTreeModel, SWATCH_BACKDROP_GEOSET, SWATCH_TEXELS, swatchCentre, SWATCHES, swatchTexture, TREE, TREE_POSES, TREE_SKELETON, TREE_BLEND_MS, TREE_BOB_HEIGHT, TREE_GUST_DEGREES, TREE_SOLID_COLOURS, TREE_SWAY_DEGREES, TREE_SWAY_TIMES, treeAnimation, treeSwayTracks, treeTexture } from './fixtures';
export type { ModelTexture, SwatchSpec, SwatchTexel } from './fixtures';
export { billboardCameraIn, boneLocalMatrix, bonePivotPosition, computeBoneMatrices, MAX_BONES, NO_PARENT, REST_POSE, rotationPose, SKELETON_AXIS_LENGTH, SKELETON_LINK_COLOUR, skeletonLines, skinNormal, skinPosition, validateSkeleton, validateSkinning } from './skeleton';
export type { BillboardCamera, Bone, BoneBillboard, BonePose, Skeleton } from './skeleton';
export { findKeys, ROTATION_COMPONENTS, sampleBonePose, samplePoses, sampleQuatTrack, sampleVec3Track, SCALE_COMPONENTS, trackTime, TRANSLATION_COMPONENTS, validateBoneTracks, validateTrack } from './animation';
export type { BoneTracks, GlobalClock, KeySpan, Track, TrackInterpolation } from './animation';
export { AnimationPlayer, blendPose, crossFadeFactor, sequenceTime, validateModelAnimation } from './sequence';
export type { AnimationState, ModelAnimation, Sequence } from './sequence';
export { ALPHA_KEY_REFERENCE, DEFAULT_MATERIAL, FOG_POLICY_COLOUR, materialState, MODEL_BLEND, MODEL_BLEND_NAMES, modelMaterials, modelSubmeshes, RENDER_FLAG, validateModelSections } from './material';
export type { MaterialState, ModelFogPolicy, ModelMaterial, ModelSubmesh } from './material';
export { attachmentMatrix, findAttachment, validateAttachments } from './attachment';
export type { Attachment } from './attachment';
export { MAX_PARTICLES, PARTICLE_VERTEX_FLOATS, particleCapacity, particleQuadIndices, ParticleSystem, validateParticleEmitter } from './particles';
export type { ParticleEmitter } from './particles';
export { MAX_RIBBON_EDGES, RIBBON_VERTEX_FLOATS, ribbonCapacity, ribbonStripIndices, RibbonTrail, validateRibbonEmitter } from './ribbon';
export type { RibbonEmitter } from './ribbon';
export { DEFAULT_UNITS_PER_YARD, MODEL_FADE_BUCKETS, modelDistanceFade, modelFadeBucket } from './distanceFade';
export type { ModelFadeBucket } from './distanceFade';
export { addLoft, loftRing, loftTriangleCount } from './loft';
export type { LoftRing, LoftShape, LoftTextureRect } from './loft';
