import * as esbuild from 'esbuild';
import fs from 'node:fs';
const root=new URL('../',import.meta.url),files=['human-male-hero-lod0.glb','human-male-hero-lod1.glb','human-male-hero-lod2.glb'];
const glbs=files.map(f=>fs.readFileSync(new URL('assets/pilots/'+f,root)).toString('base64'));
const bundle=await esbuild.build({entryPoints:[new URL('pilot-viewer.js',import.meta.url).pathname.replace(/^\/([A-Z]:)/,'$1')],bundle:true,minify:true,format:'iife',write:false,target:['es2020']});
const actions=['Idle','Walk','Run','Attack','Hit','Death'];
const html=`<!doctype html><html lang="fr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Orvalis — pilote humain masculin</title><style>
*{box-sizing:border-box}html,body,canvas{width:100%;height:100%;margin:0;overflow:hidden}body{background:#111a26;color:#f2e5cd;font:16px system-ui;opacity:0;transition:opacity .3s}body.ready{opacity:1}canvas{display:block;touch-action:none}.panel{position:fixed;left:24px;top:24px;width:min(390px,calc(100vw - 48px));padding:20px;background:#131b26e8;border:1px solid #8b744d;border-radius:12px;box-shadow:0 18px 50px #0009;backdrop-filter:blur(8px)}h1{font:700 29px Georgia;margin:0 0 6px;color:#f3d79a}.sub{color:#aebfd0;font-size:13px;line-height:1.45}.group{display:flex;gap:7px;flex-wrap:wrap;margin-top:15px}button{border:1px solid #6c7684;background:#283545;color:#e9edf2;padding:8px 11px;border-radius:6px;cursor:pointer}button:hover,button.on{background:#9a7136;border-color:#f1c477;color:white}.stats{position:fixed;right:24px;top:24px;text-align:right;padding:10px 13px;border-radius:7px;background:#111923cc;color:#aebfd0;font-size:13px}#fps{color:#8fe088;font-weight:700}.hint{position:fixed;bottom:20px;left:50%;transform:translateX(-50%);background:#111923cc;padding:8px 13px;border-radius:20px;color:#bdc7d2;font-size:13px;white-space:nowrap}@media(max-width:650px){.panel{left:12px;top:12px;width:calc(100vw - 24px);padding:13px}.panel h1{font-size:22px}.stats{top:auto;right:12px;bottom:12px}.hint{display:none}}
</style></head><body><canvas></canvas><section class="panel"><h1>Arven, garde d’Orvalis</h1><div class="sub">Prototype original GLB produit dans Blender. Corps héroïque, visage construit, mains et doigts, vêtements en couches, matériaux PBR et squelette animé. Aucun asset de World of Warcraft.</div><div class="group">${actions.map((a,i)=>`<button data-action="${a}" class="${i?'':'on'}">${a}</button>`).join('')}</div><div class="group"><button data-lod="0" class="on">Proche</button><button data-lod="1">Moyen</button><button data-lod="2">Lointain</button></div></section><div class="stats"><div id="fps">— FPS</div><div id="meta">Chargement…</div></div><div class="hint">Glisser pour tourner · molette pour zoomer</div><script>window.__PILOT_GLB=${JSON.stringify(glbs)};</script><script>${bundle.outputFiles[0].text.replace(/<\/script/gi,'<\\/script')}</script></body></html>`;
fs.mkdirSync(new URL('dist/',root),{recursive:true});fs.writeFileSync(new URL('dist/Pilote-Humain.html',root),html);console.log('pilot build',Math.round(Buffer.byteLength(html)/1024)+' Ko');

